##plugin by DerCooleVonDem

##enter the link here
discord-link-message: "§b§lDiscord§r §7|§r §fYou can join our Discord with this link §ehttps://discord.gg/dtwdhm3dSN§r"
#check out discord.link to get a custom domain like -> "https://discord.link/cooldiscord"